### ISSUE TITLE
onclick triggered twice

### ISSUE THREAD

**Issue by melvingrootenboers** [mendix/DynamicImageViewer#7]
The onclick event is triggered twice with only one click. Reproduced in Mx7.0.2.

**Comment by JelteMX** [comment]
Check if [this version](https://github.com/mendix/DynamicImageViewer/raw/issue_7_onclick_triggered_twice/test/widgets/DynamicImage.mpk) is working accordingly

**Comment by melvingrootenboers** [comment]
Works!

**Comment by JelteMX** [comment]
Fixed in [4.3.0](https://github.com/mendix/DynamicImageViewer/releases/tag/v4.3.0)
